name: Workflow name

on: push

permissions:
  contents: read

jobs:
  test:
    name: Run C++
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        key: [123, 456, 789]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Compile C++
      run: g++ -O3 main.cpp -o main.exe
  
    - name: Run executable
      run: ./main.exe ${{ matrix.key }}
