name: Workflow name

on: push

permissions:
  contents: read

jobs:
  compile:
    name: Compile C++
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile C++
      run: g++ -O3 main.cpp -o main.exe

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: main.exe

  run:
    name: Run C++
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        key: [123, 456, 789]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download executable
      uses: actions/download-artifact@v4
      with:
        name: executable
        path: .

    - name: Run executable
      run: |
        chmod +x main.exe
        ./main.exe ${{ matrix.key }}
